import api from "../api/axios";

export const adminApi = {
  getDashboardStats: () => api.get("/admin/dashboard").then(res => res.data),
  getChartData: (params) => api.get("/admin/chart-data", { params }).then(res => res.data),
  getUsers: (params) => api.get("/admin/users", { params }).then(res => res.data),
  getUserDetail: (id) => api.get(`/admin/users/${id}`).then(res => res.data),
  createUser: (data) => api.post("/admin/users", data).then(res => res.data),
  resendUserAccountEmail: (id) => api.post(`/admin/users/${id}/resend-account-email`).then(res => res.data),
  updateUser: (id, data) => api.put(`/admin/users/${id}`, data).then(res => res.data),
  toggleUserStatus: (id) => api.put(`/admin/users/${id}/status`).then(res => res.data),
  resetUserPassword: (id, newPassword) => api.put(`/admin/users/${id}/reset-password`, { newPassword }).then(res => res.data),
  deleteUser: (id) => api.delete(`/admin/users/${id}`).then(res => res.data),
  getStudents: (params) => api.get("/admin/students", { params }).then(res => res.data),
  getSupervisors: (params) => api.get("/admin/supervisors", { params }).then(res => res.data),
  getInternships: (params) => api.get("/admin/internships", { params }).then(res => res.data),
  getReports: (params) => api.get("/admin/reports", { params }).then(res => res.data),
  updateReport: (id, data) => api.put(`/admin/reports/${id}`, data).then(res => res.data),
  getMeetings: (params) => api.get("/admin/meetings", { params }).then(res => res.data),
  createMeeting: (data) => api.post("/admin/meetings", data).then(res => res.data),
  updateMeeting: (id, data) => api.put(`/admin/meetings/${id}`, data).then(res => res.data),
  deleteMeeting: (id) => api.delete(`/admin/meetings/${id}`).then(res => res.data),
  getNotifications: (params) => api.get("/admin/notifications", { params }).then(res => res.data),
  createNotification: (data) => api.post("/admin/notifications", data).then(res => res.data),
  getDefenseAlerts: (params) => api.get("/admin/defense-alerts", { params }).then(res => res.data),
  createDefenseAlert: (data) => api.post("/admin/defense-alerts", data).then(res => res.data),
  updateDefenseAlert: (id, data) => api.put(`/admin/defense-alerts/${id}`, data).then(res => res.data),
  importCSV: (formData) => api.post("/admin/import/csv", formData, {
    headers: { "Content-Type": "multipart/form-data" },
  }).then(res => res.data),
  getTimelines: () => api.get("/admin/timeline").then(res => res.data),
  createTimeline: (data) => api.post("/admin/timeline", data).then(res => res.data),
  updateTimeline: (id, data) => api.put(`/admin/timeline/${id}`, data).then(res => res.data),
  deleteTimeline: (id) => api.delete(`/admin/timeline/${id}`).then(res => res.data),
};
